"""empty message

Revision ID: 53774b18a759
Revises: 
Create Date: 2017-10-18 14:34:51.421172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53774b18a759'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idcode', sa.String(length=164), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_idcode'), 'users', ['idcode'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_idcode'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
